import { ChromaItem } from "../ui/ChromaGrid";

export const chromaGridDemo: ChromaItem[] = [
  {
    image: "/images/team/avril.jpg",
    title: "Avril Nur Adi Pratama",
    subtitle: "Purwokerto",
    borderColor: "#4F46E5",
    gradient: "linear-gradient(145deg,#4F46E5,#000)",
  },
  {
    image: "/images/team/miranda.jpg",
    title: "Miranda Septalia",
    subtitle: "Tegal",
    borderColor: "#10B981",
    gradient: "linear-gradient(210deg,#10B981,#000)",
  },
  {
    image: "/images/team/nopri.jpg",
    title: "Nopri Anita Libertiana Saragih",
    subtitle: "Medan",
    borderColor: "#F59E0B",
    gradient: "linear-gradient(165deg,#F59E0B,#000)",
  },
  {
    image: "/images/team/habib.jpg",
    title: "Habib Rafi'i",
    subtitle: "Cilacap",
    borderColor: "#EF4444",
    gradient: "linear-gradient(195deg,#EF4444,#000)",
  },
  {
    image: "/images/team/ikhsan.jpg",
    title: "Ikhsan Bachtiar",
    subtitle: "Boyolali",
    borderColor: "#8B5CF6",
    gradient: "linear-gradient(225deg,#8B5CF6,#000)",
  },
  {
    image: "/images/team/hamka.jpg",
    title: "Hamka Zainul Ardi",
    subtitle: "Brebes",
    borderColor: "#06B6D4",
    gradient: "linear-gradient(135deg,#06B6D4,#000)",
  },
  {
    image: "/images/team/ching.jpg",
    title: "Chhoun Seachhing",
    subtitle: "Kamboja",
    borderColor: "#4F46E5",
    gradient: "linear-gradient(145deg,#4F46E5,#000)",
  },
  {
    image: "/images/team/zaa.jpg",
    title: "Khorn Chanpiriza",
    subtitle: "Kamboja",
    borderColor: "#10B981",
    gradient: "linear-gradient(210deg,#10B981,#000)",
  },
  {
    image: "/images/team/afik.jpg",
    title: "Afik Anwar Firdaus",
    subtitle: "Purwokerto",
    borderColor: "#F59E0B",
    gradient: "linear-gradient(165deg,#F59E0B,#000)",
  },
  {
    image: "/images/team/asbi.jpg",
    title: "M Asbi Ramadhan",
    subtitle: "Lampung",
    borderColor: "#EF4444",
    gradient: "linear-gradient(195deg,#EF4444,#000)",
  },
  {
    image: "/images/team/cinta.jpg",
    title: "Cinta Alodya Putri Permadi",
    subtitle: "Purwokerto",
    borderColor: "#8B5CF6",
    gradient: "linear-gradient(225deg,#8B5CF6,#000)",
  },
  {
    image: "/images/team/dimas.jpg",
    title: "Dimas Sakti Laksana Putra",
    subtitle: "Purwokerto",
    borderColor: "#06B6D4",
    gradient: "linear-gradient(135deg,#06B6D4,#000)",
  },
  {
    image: "/images/team/siti.jpg",
    title: "Siti Aulia Demisya Putri",
    subtitle: "Padang",
    borderColor: "#4F46E5",
    gradient: "linear-gradient(145deg,#4F46E5,#000)",
  },
  {
    image: "/images/team/ali.jpg",
    title: "M Ali Ramadhan",
    subtitle: "Purwokerto",
    borderColor: "#10B981",
    gradient: "linear-gradient(210deg,#10B981,#000)",
  },
  {
    image: "/images/team/hana.jpg",
    title: "Happyana Kumara Jaya Lestari",
    subtitle: "Jakarta",
    borderColor: "#F59E0B",
    gradient: "linear-gradient(165deg,#F59E0B,#000)",
  },
  {
    image: "/images/team/lita.jpg",
    title: "Lyta Madesha Maharani",
    subtitle: "Cirebon",
    borderColor: "#EF4444",
    gradient: "linear-gradient(195deg,#EF4444,#000)",
  },
  {
    image: "/images/team/eliza.jpg",
    title: "Elliza Arvinoviana Setya Kusuma",
    subtitle: "Wonogiri",
    borderColor: "#8B5CF6",
    gradient: "linear-gradient(225deg,#8B5CF6,#000)",
  },
  {
    image: "/images/team/ridho.jpg",
    title: "Ridho Pratama",
    subtitle: "Medan",
    borderColor: "#06B6D4",
    gradient: "linear-gradient(135deg,#06B6D4,#000)",
  },
  {
    image: "/images/team/rendi.jpg",
    title: "Rendi Setiawan",
    subtitle: "Bogor",
    borderColor: "#4F46E5",
    gradient: "linear-gradient(145deg,#4F46E5,#000)",
  },
  {
    image: "/images/team/tiara.jpg",
    title: "Tiara Wahyu Pangeswari",
    subtitle: "Purwokerto",
    borderColor: "#10B981",
    gradient: "linear-gradient(210deg,#10B981,#000)",
  },
  {
    image: "/images/team/sabian.jpg",
    title: "Syahzada Arsa Sabian",
    subtitle: "Brebes",
    borderColor: "#F59E0B",
    gradient: "linear-gradient(165deg,#F59E0B,#000)",
  },
  {
    image: "/images/team/rachel.jpg",
    title: "Cleresta Rachel Indah Permata",
    subtitle: "Purbalingga",
    borderColor: "#EF4444",
    gradient: "linear-gradient(195deg,#EF4444,#000)",
  },
  {
    image: "/images/team/tiaras.jpg",
    title: "Tiara Safitri Herdian",
    subtitle: "Kebumen",
    borderColor: "#8B5CF6",
    gradient: "linear-gradient(225deg,#8B5CF6,#000)",
  },
  {
    image: "/images/team/elwas.jpg",
    title: "Elwas Ridho Saebani",
    subtitle: "Solo",
    borderColor: "#06B6D4",
    gradient: "linear-gradient(135deg,#06B6D4,#000)",
  },
  {
    image: "/images/team/sendi.jpg",
    title: "Sendy Oktavian Pramada",
    subtitle: "Purbalingga",
    borderColor: "#4F46E5",
    gradient: "linear-gradient(145deg,#4F46E5,#000)",
  },
  {
    image: "/images/team/adam.jpg",
    title: "Adam Putra Mardianto",
    subtitle: "Banjarmasin",
    borderColor: "#10B981",
    gradient: "linear-gradient(210deg,#10B981,#000)",
  },
  {
    image: "/images/team/sabina.jpg",
    title: "Sabina Sweeta Maharani",
    subtitle: "Purwokerto",
    borderColor: "#F59E0B",
    gradient: "linear-gradient(165deg,#F59E0B,#000)",
  },
  {
    image: "/images/team/ade.jpg",
    title: "Ade Ananda Damanik",
    subtitle: "Medan",
    borderColor: "#EF4444",
    gradient: "linear-gradient(195deg,#EF4444,#000)",
  },
  {
    image: "/images/team/faiq.jpg",
    title: "Akhmad Faiq In'amudin",
    subtitle: "Purwokerto",
    borderColor: "#8B5CF6",
    gradient: "linear-gradient(225deg,#8B5CF6,#000)",
  },
  {
    image: "/images/team/sunu.jpg",
    title: "Sunu Risang Hanugroho",
    subtitle: "Medan",
    borderColor: "#06B6D4",
    gradient: "linear-gradient(135deg,#06B6D4,#000)",
  },
];
